linea_1 = [
    "OBSERVATORIO", "TACUBAYA", "JUANACATLÁN", "CHAPULTEPEC", "SEVILLA",
    "INSURGENTES", "CUAUHTÉMOC", "BALDERAS", "SALTO DEL AGUA", "ISABEL LA CATÓLICA",
    "PINO SUÁREZ", "MERCED", "CANDELARIA", "SAN LÁZARO", "MOCTEZUMA",
    "BALBUENA", "BOULEVARD PUERTO AÉREO", "GÓMEZ FARÍAS", "ZARAGOZA", "PANTITLÁN"
]

linea_2 = [
    "CUATRO CAMINOS", "PANTEONES", "TACUBA", "CUITLÁHUAC", "POPOTLA",
    "COLEGIO MILITAR", "NORMAL", "SAN COSME", "REVOLUCIÓN", "HIDALGO",
    "BELLAS ARTES", "ALLENDE", "ZÓCALO", "PINO SUÁREZ", "SAN ANTONIO ABAD",
    "CHABACANO", "VIADUCTO", "XOLA", "VILLA DE CORTÉS", "NATIVITAS",
    "PORTALES", "ERMITA", "GENERAL ANAYA", "TASQUEÑA"
]

linea_3 = [
    "INDIOS VERDES", "DEPORTIVO 18 DE MARZO", "POTRERO", "LA RAZA", "TEPITO",
    "GUERRERO", "HIDALGO", "JUÁREZ", "BALDERAS", "NIÑOS HÉROES",
    "HOSPITAL GENERAL", "CENTRO MÉDICO", "ETIOPÍA", "EUGENIA", "DIVISIÓN DEL NORTE",
    "ZAPATA", "COYOACÁN", "VIVEROS", "MIGUEL ÁNGEL DE QUEVEDO", "COPILCO",
    "UNIVERSIDAD"
]

linea_4 = [
    "MARTÍN CARRERA", "TALISMÁN", "BONDOJITO", "CONSULADO", "CANAL DEL NORTE",
    "MORELOS", "CANDALÁRIA", "FRAY SERVANDO", "JAMAICA", "SANTA ANITA"
]

linea_5 = [
    "POLITECNICO", "INSTITUTO DEL PETRÓLEO", "AUTOBUSES DEL NORTE", "LA RAZA",
    "MISTERIOS", "VALLE GÓMEZ", "CONSULADO", "EDUARDO MOLINA", "ARAGÓN",
    "OCEANÍA", "TERMINAL AÉREA", "HANGARES", "PANTITLÁN"
]

linea_6 = [
    "EL ROSARIO", "TEZOZOMOC", "AZCAPOTZALCO", "FERRERÍA", "NORTE 45", "VALLEJO",
    "INSTITUTO DEL PETRÓLEO", "LINDAVISTA", "DEPORTIVO 18 DE MARZO",
    "LA VILLA-BASÍLICA", "MARTÍN CARRERA"
]

linea_7 = [
    "EL ROSARIO", "AQUILES SERDÁN", "CAMARONES", "REFINERÍA", "TACUBA",
    "SAN JOAQUÍN", "POLANCO", "AUDITORIO", "CONSTITUYENTES", "TACUBAYA",
    "SAN PEDRO DE LOS PINOS", "SAN ANTONIO", "MIXCOAC", "BARRANCA DEL MUERTO"
]

linea_8 = [
    "GARIBALDI", "BELLAS ARTES", "SAN JUAN DE LETRÁN", "SALTO DEL AGUA",
    "DOCTORES", "OBRERA", "CHABACANO", "LA VIGA", "SANTA ANITA", "COYUYA",
    "IZTACALCO", "APATLACO", "ACULCO", "ESCUADRÓN 201", "ATLALILCO",
    "IZTAPALAPA", "CERRO DE LA ESTRELLA", "UAM-I", "CONSTITUCIÓN DE 1917"
]
linea_9 = [
    "PANTITLÁN", "PUEBLA", "CIUDAD DEPORTIVA", "VELODROMO", "MIXIUHCA",
    "JAMAICA", "CHABACANO", "LAZARO CÁRDENAS", "CENTRO MÉDICO", "CHILPANCINGO",
    "PATRIOTISMO", "TACUBAYA"
]

linea_A = [
    "PANTITLÁN", "AGRÍCOLA ORIENTAL", "CANAL DE SAN JUAN", "TEPALCATES",
    "GUELATAO", "PEÑÓN VIEJO", "ACATITLA", "SANTA MARTA", "LOS REYES", "LA PAZ"
]

linea_B = [
    "CIUDAD AZTECA", "PLAZA ARAGÓN", "OLÍMPICA", "ECATEPEC", "MUZQUIZ",
    "RÍO DE LOS REMEDIOS", "IMPULSORA", "NEZAHUALCÓYOTL", "VILLA DE ARAGÓN",
    "BOSQUES DE ARAGÓN", "DEPORTIVO OCEANÍA", "OCEANÍA", "ROMERO RUBIO",
    "RICARDO FLORES MAGÓN", "SAN LÁZARO", "MORELOS", "TEPITO", "LAGUNILLA",
    "GARIBALDI", "GUERRERO", "BUENAVISTA"
]

linea_12 = [
    "MIXCOAC", "INSURGENTES SUR", "HOSPITAL 20 DE NOVIEMBRE", "ZAPATA",
    "PARQUE DE LOS VENADOS", "EJE CENTRAL", "ERMITA", "MEXICALTZINGO",
    "ATLALILCO", "CULHUACÁN", "SAN ANDRÉS TOMATLÁN", "LOMAS ESTRELLA",
    "CALLE 11", "PERIFÉRICO ORIENTE", "TEZONCO", "OLIVOS", "NOPALERA",
    "ZAPOTITLÁN", "TLALTENCO", "TLÁHUAC"
]